// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Protocol_i.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Example {

  /// <summary>Holder for reflection information generated from proto/Protocol_i.proto</summary>
  public static partial class ProtocolIReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/Protocol_i.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolIReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZwcm90by9Qcm90b2NvbF9pLnByb3RvIjUKB0FnZW50aWUSCgoCaWQYASAB",
            "KAMSEAoIdXNlcm5hbWUYAiABKAkSDAoEcGFzcxgDIAEoCSKWAQoIRXhjdXJz",
            "aWUSCgoCaWQYASABKAMSGQoRb2JpZWN0aXZfdHVyaXN0aWMYAiABKAkSFgoO",
            "bnVtZV90cmFuc3BvcnQYAyABKAkSEwoLb3JhX3BsZWNhcmUYBCABKAkSDAoE",
            "cHJldBgFIAEoBRIRCglucl9sb2N1cmkYBiABKAUSFQoNbG9jdXJpX2xpYmVy",
            "ZRgHIAEoBSJlCglSZXplcnZhcmUSCgoCaWQYASABKAMSEAoIZXhjdXJzaWUY",
            "AiABKAMSEwoLbnVtZV9jbGllbnQYAyABKAkSEgoKbnJfdGVsZWZvbhgEIAEo",
            "CRIRCglucl9sb2N1cmkYBSABKAUioQIKB1JlcXVlc3QSIgoEdHlwZRgBIAEo",
            "DjIULlJlcXVlc3QuUmVxdWVzdFR5cGUSGwoHYWdlbnRpZRgCIAEoCzIILkFn",
            "ZW50aWVIABIdCghleGN1cnNpZRgDIAEoCzIJLkV4Y3Vyc2llSAASHwoJcmV6",
            "ZXJ2YXJlGAQgASgLMgouUmV6ZXJ2YXJlSAAijAEKC1JlcXVlc3RUeXBlEgkK",
            "BUxPR0lOEAASCgoGTE9HT1VUEAESEQoNVVBEQVRFX1NFQVJDSBACEhAKDEdF",
            "VF9FWENVUlNJSRADEhQKEEdFVF9FWENVUlNJSV9PUkUQBBISCg5HRVRfRlJF",
            "RV9TRUFUUxAFEgsKB0FERF9SRVoQBhIKCgZHRVRfSUQQB0IGCgRkYXRhItwC",
            "CghSZXNwb25zZRIkCgR0eXBlGAEgASgOMhYuUmVzcG9uc2UuUmVzcG9uc2VU",
            "eXBlEhsKB2FnZW50aWUYAiABKAsyCC5BZ2VudGllSAASHQoIZXhjdXJzaWUY",
            "AyABKAsyCS5FeGN1cnNpZUgAEh8KCXJlemVydmFyZRgEIAEoCzIKLlJlemVy",
            "dmFyZUgAEhsKCEV4Y3Vyc2lpGAUgAygLMgkuRXhjdXJzaWUSDQoFZXJyb3IY",
            "BiABKAkimAEKDFJlc3BvbnNlVHlwZRIGCgJPSxAAEgkKBUVSUk9SEAESEQoN",
            "VVBEQVRFX1NFQVJDSBACEhQKEEZSSUVORF9MT0dHRURfSU4QAxIVChFGUklF",
            "TkRfTE9HR0VEX09VVBAEEgwKCEVYQ1VSU0lJEAUSEAoMRVhDVVJTSUlfT1JF",
            "EAYSFQoRQURERURfUkVaRVJWQVRJT04QB0IGCgRkYXRhQg6qAgtPcmcuRXhh",
            "bXBsZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.Agentie), global::Org.Example.Agentie.Parser, new[]{ "Id", "Username", "Pass" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.Excursie), global::Org.Example.Excursie.Parser, new[]{ "Id", "ObiectivTuristic", "NumeTransport", "OraPlecare", "Pret", "NrLocuri", "LocuriLibere" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.Rezervare), global::Org.Example.Rezervare.Parser, new[]{ "Id", "Excursie", "NumeClient", "NrTelefon", "NrLocuri" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.Request), global::Org.Example.Request.Parser, new[]{ "Type", "Agentie", "Excursie", "Rezervare" }, new[]{ "Data" }, new[]{ typeof(global::Org.Example.Request.Types.RequestType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.Response), global::Org.Example.Response.Parser, new[]{ "Type", "Agentie", "Excursie", "Rezervare", "Excursii", "Error" }, new[]{ "Data" }, new[]{ typeof(global::Org.Example.Response.Types.ResponseType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Agentie : pb::IMessage<Agentie>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Agentie> _parser = new pb::MessageParser<Agentie>(() => new Agentie());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Agentie> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolIReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Agentie() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Agentie(Agentie other) : this() {
      id_ = other.id_;
      username_ = other.username_;
      pass_ = other.pass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Agentie Clone() {
      return new Agentie(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pass" field.</summary>
    public const int PassFieldNumber = 3;
    private string pass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Pass {
      get { return pass_; }
      set {
        pass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Agentie);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Agentie other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Username != other.Username) return false;
      if (Pass != other.Pass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Pass.Length != 0) hash ^= Pass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Pass.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Pass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Pass.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Pass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Pass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Pass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Agentie other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Pass.Length != 0) {
        Pass = other.Pass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Pass = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Pass = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Excursie : pb::IMessage<Excursie>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Excursie> _parser = new pb::MessageParser<Excursie>(() => new Excursie());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Excursie> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolIReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie(Excursie other) : this() {
      id_ = other.id_;
      obiectivTuristic_ = other.obiectivTuristic_;
      numeTransport_ = other.numeTransport_;
      oraPlecare_ = other.oraPlecare_;
      pret_ = other.pret_;
      nrLocuri_ = other.nrLocuri_;
      locuriLibere_ = other.locuriLibere_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie Clone() {
      return new Excursie(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "obiectiv_turistic" field.</summary>
    public const int ObiectivTuristicFieldNumber = 2;
    private string obiectivTuristic_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObiectivTuristic {
      get { return obiectivTuristic_; }
      set {
        obiectivTuristic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nume_transport" field.</summary>
    public const int NumeTransportFieldNumber = 3;
    private string numeTransport_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeTransport {
      get { return numeTransport_; }
      set {
        numeTransport_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ora_plecare" field.</summary>
    public const int OraPlecareFieldNumber = 4;
    private string oraPlecare_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OraPlecare {
      get { return oraPlecare_; }
      set {
        oraPlecare_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pret" field.</summary>
    public const int PretFieldNumber = 5;
    private int pret_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Pret {
      get { return pret_; }
      set {
        pret_ = value;
      }
    }

    /// <summary>Field number for the "nr_locuri" field.</summary>
    public const int NrLocuriFieldNumber = 6;
    private int nrLocuri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    /// <summary>Field number for the "locuri_libere" field.</summary>
    public const int LocuriLibereFieldNumber = 7;
    private int locuriLibere_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LocuriLibere {
      get { return locuriLibere_; }
      set {
        locuriLibere_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Excursie);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Excursie other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ObiectivTuristic != other.ObiectivTuristic) return false;
      if (NumeTransport != other.NumeTransport) return false;
      if (OraPlecare != other.OraPlecare) return false;
      if (Pret != other.Pret) return false;
      if (NrLocuri != other.NrLocuri) return false;
      if (LocuriLibere != other.LocuriLibere) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (ObiectivTuristic.Length != 0) hash ^= ObiectivTuristic.GetHashCode();
      if (NumeTransport.Length != 0) hash ^= NumeTransport.GetHashCode();
      if (OraPlecare.Length != 0) hash ^= OraPlecare.GetHashCode();
      if (Pret != 0) hash ^= Pret.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (LocuriLibere != 0) hash ^= LocuriLibere.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObiectivTuristic);
      }
      if (NumeTransport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeTransport);
      }
      if (OraPlecare.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OraPlecare);
      }
      if (Pret != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Pret);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuri);
      }
      if (LocuriLibere != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(LocuriLibere);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObiectivTuristic);
      }
      if (NumeTransport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeTransport);
      }
      if (OraPlecare.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OraPlecare);
      }
      if (Pret != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Pret);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuri);
      }
      if (LocuriLibere != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(LocuriLibere);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (ObiectivTuristic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObiectivTuristic);
      }
      if (NumeTransport.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeTransport);
      }
      if (OraPlecare.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OraPlecare);
      }
      if (Pret != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pret);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (LocuriLibere != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LocuriLibere);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Excursie other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.ObiectivTuristic.Length != 0) {
        ObiectivTuristic = other.ObiectivTuristic;
      }
      if (other.NumeTransport.Length != 0) {
        NumeTransport = other.NumeTransport;
      }
      if (other.OraPlecare.Length != 0) {
        OraPlecare = other.OraPlecare;
      }
      if (other.Pret != 0) {
        Pret = other.Pret;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      if (other.LocuriLibere != 0) {
        LocuriLibere = other.LocuriLibere;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 26: {
            NumeTransport = input.ReadString();
            break;
          }
          case 34: {
            OraPlecare = input.ReadString();
            break;
          }
          case 40: {
            Pret = input.ReadInt32();
            break;
          }
          case 48: {
            NrLocuri = input.ReadInt32();
            break;
          }
          case 56: {
            LocuriLibere = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 26: {
            NumeTransport = input.ReadString();
            break;
          }
          case 34: {
            OraPlecare = input.ReadString();
            break;
          }
          case 40: {
            Pret = input.ReadInt32();
            break;
          }
          case 48: {
            NrLocuri = input.ReadInt32();
            break;
          }
          case 56: {
            LocuriLibere = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Rezervare : pb::IMessage<Rezervare>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rezervare> _parser = new pb::MessageParser<Rezervare>(() => new Rezervare());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Rezervare> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolIReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezervare() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezervare(Rezervare other) : this() {
      id_ = other.id_;
      excursie_ = other.excursie_;
      numeClient_ = other.numeClient_;
      nrTelefon_ = other.nrTelefon_;
      nrLocuri_ = other.nrLocuri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezervare Clone() {
      return new Rezervare(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "excursie" field.</summary>
    public const int ExcursieFieldNumber = 2;
    private long excursie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Excursie {
      get { return excursie_; }
      set {
        excursie_ = value;
      }
    }

    /// <summary>Field number for the "nume_client" field.</summary>
    public const int NumeClientFieldNumber = 3;
    private string numeClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeClient {
      get { return numeClient_; }
      set {
        numeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nr_telefon" field.</summary>
    public const int NrTelefonFieldNumber = 4;
    private string nrTelefon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NrTelefon {
      get { return nrTelefon_; }
      set {
        nrTelefon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nr_locuri" field.</summary>
    public const int NrLocuriFieldNumber = 5;
    private int nrLocuri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Rezervare);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Rezervare other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Excursie != other.Excursie) return false;
      if (NumeClient != other.NumeClient) return false;
      if (NrTelefon != other.NrTelefon) return false;
      if (NrLocuri != other.NrLocuri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Excursie != 0L) hash ^= Excursie.GetHashCode();
      if (NumeClient.Length != 0) hash ^= NumeClient.GetHashCode();
      if (NrTelefon.Length != 0) hash ^= NrTelefon.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Excursie != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Excursie);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeClient);
      }
      if (NrTelefon.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NrTelefon);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Excursie != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Excursie);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeClient);
      }
      if (NrTelefon.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NrTelefon);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Excursie != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Excursie);
      }
      if (NumeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeClient);
      }
      if (NrTelefon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NrTelefon);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Rezervare other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Excursie != 0L) {
        Excursie = other.Excursie;
      }
      if (other.NumeClient.Length != 0) {
        NumeClient = other.NumeClient;
      }
      if (other.NrTelefon.Length != 0) {
        NrTelefon = other.NrTelefon;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Excursie = input.ReadInt64();
            break;
          }
          case 26: {
            NumeClient = input.ReadString();
            break;
          }
          case 34: {
            NrTelefon = input.ReadString();
            break;
          }
          case 40: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Excursie = input.ReadInt64();
            break;
          }
          case 26: {
            NumeClient = input.ReadString();
            break;
          }
          case 34: {
            NrTelefon = input.ReadString();
            break;
          }
          case 40: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolIReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.DataCase) {
        case DataOneofCase.Agentie:
          Agentie = other.Agentie.Clone();
          break;
        case DataOneofCase.Excursie:
          Excursie = other.Excursie.Clone();
          break;
        case DataOneofCase.Rezervare:
          Rezervare = other.Rezervare.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Org.Example.Request.Types.RequestType type_ = global::Org.Example.Request.Types.RequestType.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.Request.Types.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "agentie" field.</summary>
    public const int AgentieFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.Agentie Agentie {
      get { return dataCase_ == DataOneofCase.Agentie ? (global::Org.Example.Agentie) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Agentie;
      }
    }

    /// <summary>Field number for the "excursie" field.</summary>
    public const int ExcursieFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.Excursie Excursie {
      get { return dataCase_ == DataOneofCase.Excursie ? (global::Org.Example.Excursie) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Excursie;
      }
    }

    /// <summary>Field number for the "rezervare" field.</summary>
    public const int RezervareFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.Rezervare Rezervare {
      get { return dataCase_ == DataOneofCase.Rezervare ? (global::Org.Example.Rezervare) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Rezervare;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Agentie = 2,
      Excursie = 3,
      Rezervare = 4,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Agentie, other.Agentie)) return false;
      if (!object.Equals(Excursie, other.Excursie)) return false;
      if (!object.Equals(Rezervare, other.Rezervare)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Org.Example.Request.Types.RequestType.Login) hash ^= Type.GetHashCode();
      if (dataCase_ == DataOneofCase.Agentie) hash ^= Agentie.GetHashCode();
      if (dataCase_ == DataOneofCase.Excursie) hash ^= Excursie.GetHashCode();
      if (dataCase_ == DataOneofCase.Rezervare) hash ^= Rezervare.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Org.Example.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Agentie) {
        output.WriteRawTag(18);
        output.WriteMessage(Agentie);
      }
      if (dataCase_ == DataOneofCase.Excursie) {
        output.WriteRawTag(26);
        output.WriteMessage(Excursie);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        output.WriteRawTag(34);
        output.WriteMessage(Rezervare);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Org.Example.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Agentie) {
        output.WriteRawTag(18);
        output.WriteMessage(Agentie);
      }
      if (dataCase_ == DataOneofCase.Excursie) {
        output.WriteRawTag(26);
        output.WriteMessage(Excursie);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        output.WriteRawTag(34);
        output.WriteMessage(Rezervare);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Org.Example.Request.Types.RequestType.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (dataCase_ == DataOneofCase.Agentie) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Agentie);
      }
      if (dataCase_ == DataOneofCase.Excursie) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Excursie);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rezervare);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Org.Example.Request.Types.RequestType.Login) {
        Type = other.Type;
      }
      switch (other.DataCase) {
        case DataOneofCase.Agentie:
          if (Agentie == null) {
            Agentie = new global::Org.Example.Agentie();
          }
          Agentie.MergeFrom(other.Agentie);
          break;
        case DataOneofCase.Excursie:
          if (Excursie == null) {
            Excursie = new global::Org.Example.Excursie();
          }
          Excursie.MergeFrom(other.Excursie);
          break;
        case DataOneofCase.Rezervare:
          if (Rezervare == null) {
            Rezervare = new global::Org.Example.Rezervare();
          }
          Rezervare.MergeFrom(other.Rezervare);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Org.Example.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Org.Example.Agentie subBuilder = new global::Org.Example.Agentie();
            if (dataCase_ == DataOneofCase.Agentie) {
              subBuilder.MergeFrom(Agentie);
            }
            input.ReadMessage(subBuilder);
            Agentie = subBuilder;
            break;
          }
          case 26: {
            global::Org.Example.Excursie subBuilder = new global::Org.Example.Excursie();
            if (dataCase_ == DataOneofCase.Excursie) {
              subBuilder.MergeFrom(Excursie);
            }
            input.ReadMessage(subBuilder);
            Excursie = subBuilder;
            break;
          }
          case 34: {
            global::Org.Example.Rezervare subBuilder = new global::Org.Example.Rezervare();
            if (dataCase_ == DataOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Org.Example.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Org.Example.Agentie subBuilder = new global::Org.Example.Agentie();
            if (dataCase_ == DataOneofCase.Agentie) {
              subBuilder.MergeFrom(Agentie);
            }
            input.ReadMessage(subBuilder);
            Agentie = subBuilder;
            break;
          }
          case 26: {
            global::Org.Example.Excursie subBuilder = new global::Org.Example.Excursie();
            if (dataCase_ == DataOneofCase.Excursie) {
              subBuilder.MergeFrom(Excursie);
            }
            input.ReadMessage(subBuilder);
            Excursie = subBuilder;
            break;
          }
          case 34: {
            global::Org.Example.Rezervare subBuilder = new global::Org.Example.Rezervare();
            if (dataCase_ == DataOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("LOGOUT")] Logout = 1,
        [pbr::OriginalName("UPDATE_SEARCH")] UpdateSearch = 2,
        [pbr::OriginalName("GET_EXCURSII")] GetExcursii = 3,
        [pbr::OriginalName("GET_EXCURSII_ORE")] GetExcursiiOre = 4,
        [pbr::OriginalName("GET_FREE_SEATS")] GetFreeSeats = 5,
        [pbr::OriginalName("ADD_REZ")] AddRez = 6,
        [pbr::OriginalName("GET_ID")] GetId = 7,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolIReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      excursii_ = other.excursii_.Clone();
      error_ = other.error_;
      switch (other.DataCase) {
        case DataOneofCase.Agentie:
          Agentie = other.Agentie.Clone();
          break;
        case DataOneofCase.Excursie:
          Excursie = other.Excursie.Clone();
          break;
        case DataOneofCase.Rezervare:
          Rezervare = other.Rezervare.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Org.Example.Response.Types.ResponseType type_ = global::Org.Example.Response.Types.ResponseType.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.Response.Types.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "agentie" field.</summary>
    public const int AgentieFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.Agentie Agentie {
      get { return dataCase_ == DataOneofCase.Agentie ? (global::Org.Example.Agentie) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Agentie;
      }
    }

    /// <summary>Field number for the "excursie" field.</summary>
    public const int ExcursieFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.Excursie Excursie {
      get { return dataCase_ == DataOneofCase.Excursie ? (global::Org.Example.Excursie) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Excursie;
      }
    }

    /// <summary>Field number for the "rezervare" field.</summary>
    public const int RezervareFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.Rezervare Rezervare {
      get { return dataCase_ == DataOneofCase.Rezervare ? (global::Org.Example.Rezervare) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Rezervare;
      }
    }

    /// <summary>Field number for the "Excursii" field.</summary>
    public const int ExcursiiFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Org.Example.Excursie> _repeated_excursii_codec
        = pb::FieldCodec.ForMessage(42, global::Org.Example.Excursie.Parser);
    private readonly pbc::RepeatedField<global::Org.Example.Excursie> excursii_ = new pbc::RepeatedField<global::Org.Example.Excursie>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Example.Excursie> Excursii {
      get { return excursii_; }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 6;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Agentie = 2,
      Excursie = 3,
      Rezervare = 4,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Agentie, other.Agentie)) return false;
      if (!object.Equals(Excursie, other.Excursie)) return false;
      if (!object.Equals(Rezervare, other.Rezervare)) return false;
      if(!excursii_.Equals(other.excursii_)) return false;
      if (Error != other.Error) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Org.Example.Response.Types.ResponseType.Ok) hash ^= Type.GetHashCode();
      if (dataCase_ == DataOneofCase.Agentie) hash ^= Agentie.GetHashCode();
      if (dataCase_ == DataOneofCase.Excursie) hash ^= Excursie.GetHashCode();
      if (dataCase_ == DataOneofCase.Rezervare) hash ^= Rezervare.GetHashCode();
      hash ^= excursii_.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Org.Example.Response.Types.ResponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Agentie) {
        output.WriteRawTag(18);
        output.WriteMessage(Agentie);
      }
      if (dataCase_ == DataOneofCase.Excursie) {
        output.WriteRawTag(26);
        output.WriteMessage(Excursie);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        output.WriteRawTag(34);
        output.WriteMessage(Rezervare);
      }
      excursii_.WriteTo(output, _repeated_excursii_codec);
      if (Error.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Org.Example.Response.Types.ResponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Agentie) {
        output.WriteRawTag(18);
        output.WriteMessage(Agentie);
      }
      if (dataCase_ == DataOneofCase.Excursie) {
        output.WriteRawTag(26);
        output.WriteMessage(Excursie);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        output.WriteRawTag(34);
        output.WriteMessage(Rezervare);
      }
      excursii_.WriteTo(ref output, _repeated_excursii_codec);
      if (Error.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Org.Example.Response.Types.ResponseType.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (dataCase_ == DataOneofCase.Agentie) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Agentie);
      }
      if (dataCase_ == DataOneofCase.Excursie) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Excursie);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rezervare);
      }
      size += excursii_.CalculateSize(_repeated_excursii_codec);
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Org.Example.Response.Types.ResponseType.Ok) {
        Type = other.Type;
      }
      excursii_.Add(other.excursii_);
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      switch (other.DataCase) {
        case DataOneofCase.Agentie:
          if (Agentie == null) {
            Agentie = new global::Org.Example.Agentie();
          }
          Agentie.MergeFrom(other.Agentie);
          break;
        case DataOneofCase.Excursie:
          if (Excursie == null) {
            Excursie = new global::Org.Example.Excursie();
          }
          Excursie.MergeFrom(other.Excursie);
          break;
        case DataOneofCase.Rezervare:
          if (Rezervare == null) {
            Rezervare = new global::Org.Example.Rezervare();
          }
          Rezervare.MergeFrom(other.Rezervare);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Org.Example.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Org.Example.Agentie subBuilder = new global::Org.Example.Agentie();
            if (dataCase_ == DataOneofCase.Agentie) {
              subBuilder.MergeFrom(Agentie);
            }
            input.ReadMessage(subBuilder);
            Agentie = subBuilder;
            break;
          }
          case 26: {
            global::Org.Example.Excursie subBuilder = new global::Org.Example.Excursie();
            if (dataCase_ == DataOneofCase.Excursie) {
              subBuilder.MergeFrom(Excursie);
            }
            input.ReadMessage(subBuilder);
            Excursie = subBuilder;
            break;
          }
          case 34: {
            global::Org.Example.Rezervare subBuilder = new global::Org.Example.Rezervare();
            if (dataCase_ == DataOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
          case 42: {
            excursii_.AddEntriesFrom(input, _repeated_excursii_codec);
            break;
          }
          case 50: {
            Error = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Org.Example.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Org.Example.Agentie subBuilder = new global::Org.Example.Agentie();
            if (dataCase_ == DataOneofCase.Agentie) {
              subBuilder.MergeFrom(Agentie);
            }
            input.ReadMessage(subBuilder);
            Agentie = subBuilder;
            break;
          }
          case 26: {
            global::Org.Example.Excursie subBuilder = new global::Org.Example.Excursie();
            if (dataCase_ == DataOneofCase.Excursie) {
              subBuilder.MergeFrom(Excursie);
            }
            input.ReadMessage(subBuilder);
            Excursie = subBuilder;
            break;
          }
          case 34: {
            global::Org.Example.Rezervare subBuilder = new global::Org.Example.Rezervare();
            if (dataCase_ == DataOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
          case 42: {
            excursii_.AddEntriesFrom(ref input, _repeated_excursii_codec);
            break;
          }
          case 50: {
            Error = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("UPDATE_SEARCH")] UpdateSearch = 2,
        [pbr::OriginalName("FRIEND_LOGGED_IN")] FriendLoggedIn = 3,
        [pbr::OriginalName("FRIEND_LOGGED_OUT")] FriendLoggedOut = 4,
        [pbr::OriginalName("EXCURSII")] Excursii = 5,
        [pbr::OriginalName("EXCURSII_ORE")] ExcursiiOre = 6,
        [pbr::OriginalName("ADDED_REZERVATION")] AddedRezervation = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
